### ISSUE TITLE
Link to "Radare from A to Z 2015" broken

### ISSUE THREAD

**Issue by winterrdog** [radareorg/awesome-radare2#15]
Hey @XVilka ,
Great compilation, i appreciate your effort. The link to that PDF is no longer on the internet i think because i got a 404 error code. Guess it's now a broken link

**Comment by XVilka** [comment]
@winterrdog I left the project, I guess you want to tag @trufae instead.

**Comment by winterrdog** [comment]
Okay. thanks I'll do so!

**Comment by trufae** [comment]
Here's the new temporary link:

https://mega.nz/file/M11RiKID#u11gH5Z_Mo815VvCB6XUcPt8HqKD7EkLwQmAYQZ0h_Y

I will fix the links when i have some spare time. Thanks @XVilka for the heads out and the work done.
