### ISSUE TITLE
Move under radareorg ?

### ISSUE THREAD

**Issue by XVilka** [radareorg/awesome-radare2#4]
It makes sense, imho

**Comment by XVilka** [comment]
cc @radare @Maijin

**Comment by radare** [comment]
what about moving it into the book?

**Comment by XVilka** [comment]
@radare IMHO it is useless in the book, totally different goal and format.

**Comment by dukebarman** [comment]
Agree about the book.

**Comment by radare** [comment]
sgtm

**Comment by XVilka** [comment]
@dukebarman can you give me admin rights for this repository please, I will transfer into radareorg organization then.

**Comment by dukebarman** [comment]
Completed
